---
- name: "[BREAK-FIX] download addon"
  unarchive:
    src: "{{ addon_url }}"
    dest: "{{ openshift_home }}"
    remote_src: yes

- name: "[BREAK-FIX] addon: replace template paths"
  replace:
    path: "{{ openshift_home }}/break-fix/break-fix.addon"
    regexp: '(.*) ([\w\-]*)\-template\.yaml'
    replace: '\1 {{ openshift_home }}/break-fix/\2-template.yaml'

- name: "[BREAK-FIX] addon: remove comments and empty lines"
  lineinfile:
    path: "{{ openshift_home }}/break-fix/break-fix.addon"
    regexp: '(^\n$)|(^#.*$)'
    state: absent

- name: "[BREAK-FIX] load addon"
  shell: >
    cat {{ openshift_home }}/break-fix/break-fix.addon
  register: deploy_file

- name: "[BREAK-FIX] update script with addon content"
  lineinfile:
    path: "{{ openshift_home }}/start.sh"
    line: "sudo {{ item }}"
    state: present
  with_items: "{{ deploy_file.stdout_lines }}"

- name: "[BREAK-FIX] START"
  shell: "{{ openshift_home }}/start.sh"
