apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: scoreboard-template
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    ports:
    - name: web
      port: 8080
    - name: ws
      port: 40510
    selector:
      app: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    port:
      targetPort: web
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${APP_NAME}
    name: ws-${APP_NAME}
  spec:
    port:
      targetPort: ws
    to:
      kind: Service
      name: ${APP_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP_NAME}
    name: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
      deploymentconfig: ${APP_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: ${APP_NAME}
          deploymentconfig: ${APP_NAME}
      spec:
        containers:
        - env:
          - name: DB_PATH
            value: /data
          - name: WS_ROUTE_PREFIX
            value: "ws-"
          - name: WS_ROUTE_PORT
            value: "80"
          name: ${APP_NAME}
          image: ruromero/scoreboard:3.11
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: data
            mountPath: /data
        volumes:
        - name: data
          emptyDir: {}
    triggers:
    - type: ConfigChange
parameters:
- description: Break & Fix Application name
  displayName: Application name
  name: APP_NAME
  required: true
  value: scoreboard