---
- name: "[OPENSHIFT] install packages"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - docker
    - wget
    - screen

- name: "[OPENSHIFT] add insecure registry"
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: "[OPENSHIFT] start docker"
  service:
    name: docker
    state: started
    enabled: yes

- name: "[OPENSHIFT] configure firewall"
  firewalld:
    port: 8443/tcp
    state: enabled
    immediate: yes
    permanent: yes

- name: "[OPENSHIFT] create openshift data folder"
  file:
    path: "{{ openshift_home }}/data"
    state: directory

- name: "[OPENSHIFT] download oc client"
  unarchive:
    src: "{{ oc_client_url }}"
    dest: "{{ openshift_home }}"
    remote_src: yes
    mode: 0777

- name: "[OPENSHIFT] add oc to /usr/bin"
  file:
    src: "{{ openshift_home }}/{{ oc_client_name }}/oc"
    dest: /usr/bin/oc
    state: link

- name: "[OPENSHIFT] create start cluster script"
  copy:
    src: files/start.sh
    dest: "{{ openshift_home }}/start.sh"
    mode: 0777
