---
- name: "[OPENSHIFT] install packages"
  package:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - docker
    - wget
    - screen

- name: "[OPENSHIFT] add insecure registry"
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: "[OPENSHIFT] start docker"
  service:
    name: docker
    state: started
    enabled: yes

- name: "[OPENSHIFT] configure firewall"
  firewalld:
    port: 8443/tcp
    state: enabled
    immediate: yes
    permanent: yes

- name: "[OPENSHIFT] download oc client"
  unarchive:
    src: "{{ oc_client_url }}"
    dest: "{{ ansible_env.HOME }}"
    remote_src: yes

- name: "[OPENSHIFT] add oc to /usr/bin"
  file:
    src: "{{ ansible_env.HOME }}/{{ oc_client_name }}/oc"
    dest: /usr/bin/oc
    state: link

- name: "[OPENSHIFT] start cluster"
  shell: >
    oc cluster up --public-hostname="{{ ansible_host }}" --routing-suffix="{{ ansible_host }}.nip.io"
